 
version: '3.8'

services:
  frontend:
    container_name: nsi-directory-installer-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src  
    command: npm start

  backend:
    container_name: nsi-directory-installer-backend
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - PORT=3001
      - NODE_ENV=development 
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  db:
    container_name: nsi-directory-installer-database
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/setup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data: